# Generated by Django 3.1.2 on 2020-10-26 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20201012_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
